### ISSUE TITLE
Error "404 - /v1/models was not found on this server." after Colab deployment

### ISSUE THREAD

**Issue by tstaerk** [Cyclenerd/google-cloud-gcp-openai-api#15]
I deployed this via the Colab feature:
* created a project in Google Cloud Console
* set domain restricted sharing to "allow" (in this order)
* clicked "open in colab"
* deployed all steps using the play button, my openAI key was in the form sk-123-only13letters
* went to the frontend URL, in my case https://chatbot-ui-XXX-ew.a.run.app/
* only a wheel is spinning there, sometime I see the message "Error fetching models.
Make sure your OpenAI API key is set in the bottom left of the sidebar.
If you completed this step, OpenAI may be experiencing issues. Error 500"
* in the Cloud Run logs, I find an Error message "POST500666 B135 msChrome 121 https://chatbot-ui-35XXXa-ew.a.run.app/api/models "
* when I expand this, I find

```txt
{
httpRequest: {
latency: "0.135149560s"
protocol: "HTTP/1.1"
referer: "https://chatbot-ui-35XXX-ew.a.run.app/"
remoteIp: "2a02:3100:5867:8701:a596:638d:4670:c449"
requestMethod: "POST"
requestSize: "862"
requestUrl: "https://chatbot-ui-35XXX.a.run.app/api/models"
responseSize: "666"
serverIp: "2001:4860:4802:36::35"
status: 500
userAgent: "Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
}
insertId: "65a158cd0006fcb5d44be846"
labels: {
instanceId: "0087599d427185aebb313689bb408e0c88da7eaf33934605a2ff3204ad1649412c336d290dadc8458e2f8ef07655d8a216fa860c3d3d88a53cd44f259ff3202f6a9c"
}
logName: "projects/thorstenstaerk-nils2/logs/run.googleapis.com%2Frequests"
receiveTimestamp: "2024-01-12T15:20:45.618651319Z"
resource: {
labels: {
service_name: "chatbot-ui"
project_id: "thorstenstaerk-nils2"
revision_name: "chatbot-ui-00001-gfs"
configuration_name: "chatbot-ui"
location: "europe-west1"
}
type: "cloud_run_revision"
}
severity: "ERROR"
spanId: "13873342680540356080"
timestamp: "2024-01-12T15:20:45.320472Z"
trace: "projects/thorstenstaerk-nils2/traces/b4419a8dd29302b4eb53be48e42bac76"
}
```

When I look at the next messages in the log, they are not marked as Error messages, but I find one that I regard as relevant: 

  <p>The requested URL <code>/v1/models</code> was not found on this server.  <ins>That’s all we know.</ins>

**Comment by Cyclenerd** [comment]
Please check the Back-End log. Can you access the Back-End `/v1/models` URL with your browser `https://openai-api-vertex-[...].a.run.app/v1/models`?

Please also check the `OPENAI_API_HOST` in the Front-End:
![image](https://github.com/Cyclenerd/google-cloud-gcp-openai-api/assets/176242/c2c4bd77-d57c-4d97-8bf1-9dd45544587e)
It must be the Back-End URL.

**Comment by tstaerk** [comment]
thanks. I can access the back-end via my browser and get data like 


"{"data":[{"id":"gpt-3.5-turbo","object":"model","created":1705260835,"owned_by":"openai","permission":[{"id":"modelperm-0914daec524cb6e60dbf07f4","cr" and so on


OPENAI_API_HOST is https://openai-api-vertex-XYZ-AB.a.run.app was wrong, I corrected it, same error like before.

**Comment by tstaerk** [comment]
after a fresh start, it works now:
![image](https://github.com/Cyclenerd/google-cloud-gcp-openai-api/assets/325187/ec637892-0b5a-45ce-b9d6-5df35e03996d)

however I priviledged the default compute user for aiplatform.admin and vertexai.user and I enabled binary authorization and I want to see if it still works in a fresh project where I did not do this.

**Comment by tstaerk** [comment]
I tried it again with a fresh project and it did not work. Then I gave the AI Platform Admin Role and the Vertex AI user role to the default compute service account, then it worked. At the same time, the following message stopped appearing in the logs:

`google.api_core.exceptions.PermissionDenied: 403 Permission 'aiplatform.endpoints.predict' denied on resource '//aiplatform.googleapis.com/projects/thorstenstaerk-nils3/locations/us-central1/publishers/google/models/codechat-bison@002' (or it may not exist). [reason: "IAM_PERMISSION_DENIED"`

**Comment by Cyclenerd** [comment]
Thanks for testing and figuring it out. In fact, the role assignment in the notebook was missing. In the README it was written: https://github.com/Cyclenerd/google-cloud-gcp-openai-api#deploying-to-cloud-run

I have enhanced the notebook: https://github.com/Cyclenerd/google-cloud-gcp-openai-api/commit/956bccc265d6f9940c766c223515352e361de127
