### ISSUE TITLE
Feature request: Please Update Documentation with the following for Windows Users

### ISSUE THREAD

**Issue by mreid2025** [Cyclenerd/google-cloud-gcp-openai-api#17]
While deploying your program locally. I was simply converting the exports

by changing export to set.
Completely forgetting (despite a lot of years), to remove the double-quotes.  
once I did that it worked like a charm.
linux:
export DEBUG="True"
export OPENAI_API_KEY="sk-XYZ"
export MODEL_NAME="gemini-pro"

Win:
set DEBUG=True
set OPENAI_API_KEY=sk-XYZ
set MODEL_NAME=gemini-pro

I do want to thank you, this will be solving an issue with using autogen, that I was tired of messing with, and I am so grateful you wrote this api!  Thank you!

**Comment by Cyclenerd** [comment]
Thanks for the test and for letting me know. I updated the README: https://github.com/Cyclenerd/google-cloud-gcp-openai-api/commit/84ec244f8cd18e9766636a6e965544d4155fbce5
