### ISSUE TITLE
(Allow unauthenticated invocations) cannot be set. 

### ISSUE THREAD

**Issue by mhaas6** [Cyclenerd/google-cloud-gcp-openai-api#23]
After May 3rd, deploying this container as a public API (allowing unauthenticated calls) in Google Cloud Run will be disabled by default. Changing this setting requires an email address with domain management permissions, which I do not have. Is it possible to achieve public, unauthenticated access using methods like intranet penetration? 

[Translation text]

**Comment by mhaas6** [comment]
I saw other projects using 'ngrok.com' to access API ports.  I wonder if that would work? 
[Translation text]

**Comment by Cyclenerd** [comment]
That is why it is specified explicitly: https://github.com/Cyclenerd/google-cloud-gcp-openai-api/blob/master/deploy.sh#L90
